name: build sarasa2yahei
on:
  push:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git fontforge curl p7zip jq python-py7zr python-requests
        pacman -S wget




    - name: Grab latest version
      run: |
        curl -L https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest -o api.json
        UPSTREAM_VERSION=$(cat api.json | jq -r .tag_name)
        DOWNLOAD_URL=$(cat api.json | jq -r '.assets[] | select(.name | test("sarasa-gothic-ttc-(?!unhinted)")) | .browser_download_url')
        echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> $GITHUB_ENV
        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV


    # - name: Download original sarasa fonts
    #   run: curl -Lvo /tmp/sarasafonts/ttc.7z $DOWNLOAD_URL

    # - name: Extract original sarasa fonts
    #   run: 7z x -odata /tmp/sarasafonts/ttc.7z

    - name: Run script
      run: python3 sarasa2yahei.py

    # - name: Compress font
    #   run: |
    #     cd out
    #     7z a ../sarasa2yahei.7z *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sarasa2yahei
        path: /tmp/sarasafonts/out

    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "upstream-${{ env.UPSTREAM_VERSION }}"
        prerelease: false
        title: ${{ env.UPSTREAM_VERSION }}
        files: sarasa2yahei.7z
