name: build sarasa2yahei
on:
  push:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # - name: Grab latest version
    #   run: |
    #     curl -L https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest -o api.json
    #     UPSTREAM_VERSION=$(cat api.json | jq -r .tag_name)
    #     DOWNLOAD_URL=$(cat api.json | jq -r '.assets[] | select(.name | test("sarasa-gothic-ttc-(?!unhinted)")) | .browser_download_url')
    #     echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> $GITHUB_ENV
    #     echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV


    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          wget
          py7zr
          requests
          fontforge
        upgrade: true
    - run: python3 sarasa2yahei.py





    # - name: Download font
    #   run: curl -Lvo /tmp/ttc.7z $DOWNLOAD_URL

    # - name: Extract font
    #   run: 7z x -odata /tmp/ttc.7z

    # - name: Run script
    #   run: python3 sarasa2yahei.py

    # - name: Compress font
    #   run: |
    #     cd out
    #     7z a ../sarasa2yahei.7z *

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sarasa2yahei
        path: /tmp/sarasafonts/out/sarasa2yahei.7z

    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "upstream-$UPSTREAM_VERSION"
        prerelease: false
        title: $UPSTREAM_VERSION
        files: sarasa2yahei.7z
